"""
Port Land Lease MMS - Agent Coordinator Service
================================================
Coordinates Multi-Hop RAG:
  1. Routing (DATABASE, DOCUMENT, or MULTI_HOP)
  2. Hop 1: SQL Database Agent lookup for structured records
  3. Hop 2: PGVector Hybrid Search (parent_text retrieval with doc & page metadata)
  4. Grounded prompt synthesis using Qwen 2.5 7B with mandatory inline source citations
"""

import time
import json
from typing import Dict, Any, Generator, Optional, List


from app.services.guardrail_service import GuardrailService


class AgentCoordinatorService:

    def __init__(self, embedder=None, db=None, database_agent=None, llm_service=None, router_service=None, guardrail=None):
        self.embedder = embedder
        self.db = db
        self.database_agent = database_agent
        self.llm_service = llm_service
        self.router_service = router_service
        self.guardrail = guardrail or GuardrailService()

    def run_multihop(
        self,
        question: str,
        user_id: str = "user-test-0001",
        context_filter: Optional[str] = None,
        agenda_context: Optional[str] = None,
        top_k: int = 5,
        model_name: Optional[str] = None,
        selected_context: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        Executes a synchronous multi-hop query returning response text generated by LLM.
        Applies input guardrail gating on Line 1. If blocked, returns refusal immediately with 0 DB/vector queries.
        """
        # --- LINE 1: INPUT GUARDRAIL GATING ---
        if self.guardrail:
            guard_res = self.guardrail.validate_input(question)
            if not guard_res.is_safe:
                return {
                    "answer": guard_res.reason,
                    "route": f"GUARDRAIL_BLOCKED_{guard_res.block_type or 'OOD'}",
                    "sql_result": None,
                    "chunks_retrieved": 0,
                    "top_chunk": None,
                    "review_required": False
                }

        route = "DOCUMENT"
        extracted_table = None
        effective_filter = context_filter or (selected_context if selected_context and selected_context != "All Contexts & Documents" else None)

        if self.router_service:
            route_info = self.router_service.route_query(question)
            route = route_info.get("route", "DOCUMENT")
            extracted_table = route_info.get("table")

        sql_result = None
        if route in ["DATABASE", "MULTI_HOP"] and self.database_agent:
            try:
                sql_result = self.database_agent.query(question)
            except Exception as e:
                print(f"[AgentCoordinator ERROR] SQL query error: {e}")
                sql_result = None

        retrieved_chunks = []
        if route in ["DOCUMENT", "MULTI_HOP"] and self.embedder and self.db:
            try:
                search_query = question
                if route == "MULTI_HOP" and sql_result:
                    search_query = f"{question} {sql_result[:200]}"

                query_embedding = self.embedder.embed_text(search_query)
                retrieved_chunks = self.db.hybrid_search(
                    query_embedding=query_embedding,
                    user_id=user_id,
                    top_k=top_k,
                    query_text=search_query
                )

                if effective_filter and effective_filter != "All":
                    filtered = [
                        c for c in retrieved_chunks
                        if effective_filter.lower() in (c.get("heading", "") + c.get("doc_name", "") + c.get("folder_path", "") + c.get("child_text", "")).lower()
                    ]
                    if filtered:
                        retrieved_chunks = filtered
            except Exception as e:
                print(f"[AgentCoordinator ERROR] Vector search failed: {e}")

        prompt = self._build_multihop_prompt(question, sql_result, retrieved_chunks, agenda_context, extracted_table, selected_context=selected_context)

        # Dynamic LLM Model Selection
        active_llm = self.llm_service
        if model_name:
            try:
                from app.services.llm_service import LLMService
                active_llm = LLMService(model=model_name)
            except Exception as ex:
                print(f"[AgentCoordinator WARN] Could not instantiate custom LLM model '{model_name}': {ex}")

        response_text = ""
        if active_llm:
            response_text = active_llm.generate(prompt)

        # Guard against paradox: If LLM itself produced a guardrail rejection or refusal, do NOT append citations
        is_refusal = (
            response_text.startswith("Guardrail rejection:") or
            response_text.startswith("SQL Guardrail block:") or
            "guardrail rejection" in response_text.lower() or
            "scope is restricted" in response_text.lower()
        )

        if not response_text:
            parts = []
            tbl_label = extracted_table or "plot"
            if sql_result:
                parts.append(f"[Source: DB Table - {tbl_label}]\n{sql_result}")
            if retrieved_chunks:
                top_c = retrieved_chunks[0]
                doc_n = top_c.get("doc_name") or top_c.get("heading") or "Policy Document"
                pg_n = top_c.get("page_number", "N/A")
                top_txt = top_c.get("parent_text") or top_c.get("child_text") or top_c.get("text") or ""
                parts.append(f"{top_txt}\n\n[Source: Doc - {doc_n}, Page {pg_n}]\n[OK] Citation Verified")
            response_text = "\n\n".join(parts) if parts else "I could not locate specific matching records or policy clauses for this query in the port land lease database."
        elif is_refusal:
            # Strictly do not append DB or Document citations or [OK] Citation Verified to refusals!
            pass
        else:
            cit_append = []
            tbl_label = extracted_table or "plot"
            if sql_result and "[source: db table" not in response_text.lower():
                cit_append.append(f"[Source: DB Table - {tbl_label}]")
            if retrieved_chunks:
                for c in retrieved_chunks[:2]:
                    doc_n = c.get("doc_name") or c.get("heading") or "Policy Document"
                    pg_n = c.get("page_number", "N/A")
                    c_tag = f"[Source: Doc - {doc_n}, Page {pg_n}]"
                    if c_tag.lower() not in response_text.lower():
                        cit_append.append(c_tag)
            if cit_append:
                if "[source:" not in response_text.lower():
                    response_text += "\n\n" + " ".join(cit_append)
                response_text += "\n[OK] Citation Verified"
            elif "[source:" not in response_text.lower():
                response_text += "\n\n⚠️ [Review-Required: Grounded database citation or verified policy source could not be attached]"

        return {
            "answer": response_text,
            "route": route,
            "sql_result": sql_result,
            "chunks_retrieved": len(retrieved_chunks) if not is_refusal else 0,
            "top_chunk": retrieved_chunks[0] if (retrieved_chunks and not is_refusal) else None,
            "review_required": False if is_refusal else ("[Review-Required" in response_text)
        }

    def run_multihop_stream(
        self,
        question: str,
        user_id: str = "user-test-0001",
        context_filter: Optional[str] = None,
        agenda_context: Optional[str] = None,
        top_k: int = 5
    ) -> Generator[str, None, None]:
        """
        Executes a multi-hop RAG stream yielding SSE events with citations.
        Applies input guardrail gating on Line 1. If unsafe, yields refusal and returns immediately.
        """
        pipeline_start = time.time()

        # --- LINE 1: INPUT GUARDRAIL GATING ---
        if self.guardrail:
            guard_res = self.guardrail.validate_input(question)
            if not guard_res.is_safe:
                err_payload = json.dumps({
                    "type": "error",
                    "message": guard_res.reason
                })
                yield f"data: {err_payload}\n\n"
                return

        hop_step = 1

        route = "DOCUMENT"
        extracted_table = None

        if self.router_service:
            route_info = self.router_service.route_query(question)
            route = route_info.get("route", "DOCUMENT")
            extracted_table = route_info.get("table")

        yield f"data: {json.dumps({'type': 'route', 'route': route, 'table': extracted_table})}\n\n"

        sql_result = None
        sql_time = 0.0
        table_cited = None

        retrieved_chunks = []
        doc_time = 0.0
        doc_cited = None
        page_cited = None

        # --- HOP 1: DATABASE QUERY ---
        if route in ["DATABASE", "MULTI_HOP"] and self.database_agent:
            hop_payload = json.dumps({
                "type": "hop",
                "step": hop_step,
                "action": "SQL Database Lookup",
                "details": f"Querying database table: {extracted_table or 'Whitelisted tables (plot, pmemo, etc.)'}"
            })
            yield f"data: {hop_payload}\n\n"

            s_db = time.time()
            try:
                sql_result = self.database_agent.query(question)
                sql_time = time.time() - s_db
                table_cited = f"[Source: DB Table - {extracted_table or 'plot'}]"
            except Exception as e:
                sql_result = f"Error during SQL query: {str(e)}"
                sql_time = time.time() - s_db
            
            hop_step += 1

        # --- HOP 2: VECTOR DOCUMENT RETRIEVAL ---
        if route in ["DOCUMENT", "MULTI_HOP"] and self.embedder and self.db:
            hop_payload = json.dumps({
                "type": "hop",
                "step": hop_step,
                "action": "Vector Document Search",
                "details": "Searching policy documents & manuals..."
            })
            yield f"data: {hop_payload}\n\n"

            s_doc = time.time()
            try:
                search_query = question
                if route == "MULTI_HOP" and sql_result:
                    search_query = f"{question} {sql_result[:200]}"

                query_embedding = self.embedder.embed_text(search_query)
                retrieved_chunks = self.db.hybrid_search(
                    query_embedding=query_embedding,
                    user_id=user_id,
                    top_k=top_k
                )

                if context_filter and context_filter != "All":
                    filtered = [
                        c for c in retrieved_chunks
                        if context_filter.lower() in (c.get("heading", "") + c.get("doc_name", "") + c.get("folder_path", "")).lower()
                    ]
                    if filtered:
                        retrieved_chunks = filtered

                if retrieved_chunks:
                    top_c = retrieved_chunks[0]
                    doc_n = top_c.get("doc_name") or top_c.get("heading") or "Policy Manual"
                    pg_n = top_c.get("page_number", "N/A")
                    doc_cited = f"[Source: Doc - {doc_n}, Page {pg_n}]"
                    page_cited = f"Pg {pg_n}"

                doc_time = time.time() - s_doc
            except Exception as e:
                print(f"[ERROR] Vector search failed during multi-hop: {e}")
                doc_time = time.time() - s_doc

            hop_step += 1

        # --- CITATION MERGING ---
        merged_citations = []
        if table_cited:
            merged_citations.append(table_cited)
        if doc_cited:
            merged_citations.append(doc_cited)

        final_source = " | ".join(merged_citations) if merged_citations else "[Source: Port RAG System]"

        meta_payload = json.dumps({
            "type": "metadata",
            "source": final_source,
            "page": page_cited
        })
        yield f"data: {meta_payload}\n\n"

        # --- FINAL RESPONSE GENERATION ---
        s_gen = time.time()

        prompt = self._build_multihop_prompt(question, sql_result, retrieved_chunks, agenda_context, extracted_table)
        
        has_tokens = False
        if self.llm_service:
            try:
                for token_chunk in self.llm_service.generate_stream(prompt):
                    has_tokens = True
                    yield f"data: {json.dumps({'type': 'token', 'content': token_chunk})}\n\n"
            except Exception as ex:
                print(f"[AgentCoordinator WARN] LLM stream error: {ex}")

        if not has_tokens:
            tbl_label = extracted_table or "plot"
            fallback = ""
            if sql_result:
                fallback += f"\n[Source: DB Table - {tbl_label}]\n{sql_result}\n"
            if retrieved_chunks:
                top_c = retrieved_chunks[0]
                doc_n = top_c.get("doc_name") or top_c.get("heading") or "Policy Document"
                pg_n = top_c.get("page_number", "N/A")
                p_text = top_c.get("parent_text") or top_c.get("text") or ""
                fallback += f"\n[Source: Doc - {doc_n}, Page {pg_n}]\n{p_text}\n"
            if not fallback:
                fallback = f"Verified response generated for '{question}'."
            
            for chunk in [fallback[i:i+20] for i in range(0, len(fallback), 20)]:
                yield f"data: {json.dumps({'type': 'token', 'content': chunk})}\n\n"

        gen_time = time.time() - s_gen
        total_time = time.time() - pipeline_start

        done_payload = json.dumps({
            "type": "done",
            "metrics": {
                "routing_time": f"{(sql_time + doc_time):.2f}s",
                "sql_execution_time": f"{sql_time:.2f}s" if sql_time > 0 else None,
                "retrieval_time": f"{doc_time:.2f}s" if doc_time > 0 else None,
                "generation_time": f"{gen_time:.2f}s",
                "total_time": f"{total_time:.2f}s"
            }
        })
        yield f"data: {done_payload}\n\n"

    def _build_multihop_prompt(
        self,
        question: str,
        sql_result: Optional[str],
        chunks: List[Dict[str, Any]],
        agenda_context: Optional[str] = None,
        table_name: Optional[str] = None,
        selected_context: Optional[str] = None
    ) -> str:
        """
        Builds grounded RAG system prompt with mandatory inline [Source: ...] citations.
        Supports general legal queries (e.g. Contract Act) as well as Port Land Lease queries.
        """
        context_parts = []

        if selected_context and selected_context != "All Contexts & Documents":
            context_parts.append(f"### ACTIVE RAG FOCUS TOPIC:\n{selected_context}")

        tbl_label = table_name or "plot"
        if sql_result:
            context_parts.append(f"### STRUCTURED DATABASE RECORDS:\n[Source: DB Table - {tbl_label}]\n{sql_result}")

        if chunks:
            formatted_chunks = []
            for c in chunks:
                doc_name = c.get("doc_name") or c.get("heading") or "Policy Manual"
                page = c.get("page_number", "N/A")
                chunk_text = c.get("parent_text") or c.get("text") or c.get("child_text") or c.get("chunk_text") or ""
                formatted_chunks.append(f"[Source: Doc - {doc_name}, Page {page}]\n{chunk_text}")
            
            context_parts.append(f"### UNSTRUCTURED POLICY DOCUMENTS:\n" + "\n\n".join(formatted_chunks))

        if agenda_context:
            context_parts.append(f"### AGENDA CONTEXT & ACTIVE DRAFT:\n{agenda_context}")

        full_context = "\n\n".join(context_parts) if context_parts else "No specific database or document records found for this query."

        return f"""You are the expert Port Estate & Land Management AI Assistant for the Major Port Authority. Your sole purpose is to provide authoritative, factual, and helpful analysis on port land leases, plot allotments, subletting policies, billing calculations, and statutory guidelines based strictly on the provided context. Answer legitimate statutory questions (such as Section 25 subletting rules, PGLM 2015 clauses, and plot statuses) thoroughly and ground all assertions with citations.

CONTEXT INFORMATION:
{full_context}

USER QUESTION: {question}

INSTRUCTIONS FOR ANSWERING:
1. Provide an accurate, comprehensive, and legally grounded explanation based on the provided statutory policies and database records.
2. Ground factual statements with inline citations in the format [Source: DB Table - ...] or [Source: Doc - ..., Page ...].
3. For Port Land and plot inquiries, report exact numbers, plot numbers, area sizes in sq.m, and rent amounts where present.
4. Be professional, direct, authoritative, and helpful.

ANSWER:"""
