/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AiChatRouteImport } from './routes/ai-chat'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LandMonitoringRouteImport } from './routes/land-monitoring'
import { Route as AuthorityDashboardRouteImport } from './routes/authority.dashboard'
import { Route as AuthorityLoginRouteImport } from './routes/authority.login'
import { Route as TenantAiSupportRouteImport } from './routes/tenant.ai-support'
import { Route as TenantDashboardRouteImport } from './routes/tenant.dashboard'
import { Route as TenantLoginRouteImport } from './routes/tenant.login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AiChatRoute = AiChatRouteImport.update({
  id: '/ai-chat',
  path: '/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LandMonitoringRoute = LandMonitoringRouteImport.update({
  id: '/land-monitoring',
  path: '/land-monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorityDashboardRoute = AuthorityDashboardRouteImport.update({
  id: '/authority/dashboard',
  path: '/authority/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorityLoginRoute = AuthorityLoginRouteImport.update({
  id: '/authority/login',
  path: '/authority/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantAiSupportRoute = TenantAiSupportRouteImport.update({
  id: '/tenant/ai-support',
  path: '/tenant/ai-support',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantDashboardRoute = TenantDashboardRouteImport.update({
  id: '/tenant/dashboard',
  path: '/tenant/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantLoginRoute = TenantLoginRouteImport.update({
  id: '/tenant/login',
  path: '/tenant/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-chat': typeof AiChatRoute
  '/contact': typeof ContactRoute
  '/help': typeof HelpRoute
  '/land-monitoring': typeof LandMonitoringRoute
  '/authority/dashboard': typeof AuthorityDashboardRoute
  '/authority/login': typeof AuthorityLoginRoute
  '/tenant/ai-support': typeof TenantAiSupportRoute
  '/tenant/dashboard': typeof TenantDashboardRoute
  '/tenant/login': typeof TenantLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-chat': typeof AiChatRoute
  '/contact': typeof ContactRoute
  '/help': typeof HelpRoute
  '/land-monitoring': typeof LandMonitoringRoute
  '/authority/dashboard': typeof AuthorityDashboardRoute
  '/authority/login': typeof AuthorityLoginRoute
  '/tenant/ai-support': typeof TenantAiSupportRoute
  '/tenant/dashboard': typeof TenantDashboardRoute
  '/tenant/login': typeof TenantLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-chat': typeof AiChatRoute
  '/contact': typeof ContactRoute
  '/help': typeof HelpRoute
  '/land-monitoring': typeof LandMonitoringRoute
  '/authority/dashboard': typeof AuthorityDashboardRoute
  '/authority/login': typeof AuthorityLoginRoute
  '/tenant/ai-support': typeof TenantAiSupportRoute
  '/tenant/dashboard': typeof TenantDashboardRoute
  '/tenant/login': typeof TenantLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-chat'
    | '/contact'
    | '/help'
    | '/land-monitoring'
    | '/authority/dashboard'
    | '/authority/login'
    | '/tenant/ai-support'
    | '/tenant/dashboard'
    | '/tenant/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-chat'
    | '/contact'
    | '/help'
    | '/land-monitoring'
    | '/authority/dashboard'
    | '/authority/login'
    | '/tenant/ai-support'
    | '/tenant/dashboard'
    | '/tenant/login'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-chat'
    | '/contact'
    | '/help'
    | '/land-monitoring'
    | '/authority/dashboard'
    | '/authority/login'
    | '/tenant/ai-support'
    | '/tenant/dashboard'
    | '/tenant/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiChatRoute: typeof AiChatRoute
  ContactRoute: typeof ContactRoute
  HelpRoute: typeof HelpRoute
  LandMonitoringRoute: typeof LandMonitoringRoute
  AuthorityDashboardRoute: typeof AuthorityDashboardRoute
  AuthorityLoginRoute: typeof AuthorityLoginRoute
  TenantAiSupportRoute: typeof TenantAiSupportRoute
  TenantDashboardRoute: typeof TenantDashboardRoute
  TenantLoginRoute: typeof TenantLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-chat': {
      id: '/ai-chat'
      path: '/ai-chat'
      fullPath: '/ai-chat'
      preLoaderRoute: typeof AiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/land-monitoring': {
      id: '/land-monitoring'
      path: '/land-monitoring'
      fullPath: '/land-monitoring'
      preLoaderRoute: typeof LandMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authority/dashboard': {
      id: '/authority/dashboard'
      path: '/authority/dashboard'
      fullPath: '/authority/dashboard'
      preLoaderRoute: typeof AuthorityDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authority/login': {
      id: '/authority/login'
      path: '/authority/login'
      fullPath: '/authority/login'
      preLoaderRoute: typeof AuthorityLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/ai-support': {
      id: '/tenant/ai-support'
      path: '/tenant/ai-support'
      fullPath: '/tenant/ai-support'
      preLoaderRoute: typeof TenantAiSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/dashboard': {
      id: '/tenant/dashboard'
      path: '/tenant/dashboard'
      fullPath: '/tenant/dashboard'
      preLoaderRoute: typeof TenantDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/login': {
      id: '/tenant/login'
      path: '/tenant/login'
      fullPath: '/tenant/login'
      preLoaderRoute: typeof TenantLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiChatRoute: AiChatRoute,
  ContactRoute: ContactRoute,
  HelpRoute: HelpRoute,
  LandMonitoringRoute: LandMonitoringRoute,
  AuthorityDashboardRoute: AuthorityDashboardRoute,
  AuthorityLoginRoute: AuthorityLoginRoute,
  TenantAiSupportRoute: TenantAiSupportRoute,
  TenantDashboardRoute: TenantDashboardRoute,
  TenantLoginRoute: TenantLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
